language: python
python:
    - 3.7
    - 3.8
    - 3.9

install:
    - pip install coveralls

script:
    - nosetests --with-coverage --cover-tests --cover-package=pyx12 --cover-erase

after_success:
    - coveralls
